import Head from "next/head";
import { Chat, Messages, Sidebar } from "@/components";
import { useEffect, useState } from "react";
import { onAuthStateChanged } from "firebase/auth";
import { auth, db } from "@/firebase/config";
import {
  collection,
  onSnapshot,
  orderBy,
  query,
  where,
} from "firebase/firestore";
import { useGlobalChatContext } from "@/context/ChatContext";

export default function Home() {
  const { currentChat } = useGlobalChatContext();
  const [user, setUser] = useState(null);
  const [userChat, setUserChat] = useState([]);

  //   fetch users chat
  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      if (user) {
        setUser(user);
        const q = query(
          collection(db, "chats"),
          where("users", "array-contains", user?.email),
          orderBy("timestamp", "desc")
        );
        let chats = [];
        const unsubscribe = onSnapshot(q, (snapshot) => {
          snapshot.forEach((doc) => {
            chats.push({
              id: doc.id,
              data: doc.data(),
            });
            setUserChat(chats);
          });
        });
      } else {
        setUser(null);
      }
    });
  }, [userChat, user]);

  if (!user) return;

  return (
    <>
      <Head>
        <title>Whatsapp</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-[100vh] flex flex-col">
        <div className="bg-[#1b9447] h-[100px] w-full absolute top-0 left-0 " />
        <div className="h-[calc(100vh-40px)] bg-[rgb(227,230,230)] z-50 mt-[20px] mx-4 md:mx-8 flex">
          <Sidebar userChat={userChat} user={user} />
          {!currentChat ? <Chat /> : <Messages user={user} />}
        </div>
        <div className="bg-[rgb(211,208,208)] h-[100px] w-full absolute bottom-0 left-0 " />
      </main>
    </>
  );
}

export const getServerSideProps = async (context) => {
  if (!context.req?.cookies?.user) {
    return {
      redirect: {
        destination: "/auth/login",
        permanent: false,
      },
    };
  }
  return {
    props: {},
  };
};
